### ISSUE TITLE
Node support in 2.x?

### ISSUE THREAD

**Issue by tarjei** [indexeddbshim/IndexedDBShim#298] opened 2017-04-19 11:35 UTC
Hi, I tired to use IndexedDB to shim indexeddb support in jsdom for testing, but it seems that there is a mismatch between what is stated in the docs and the version that is available.

Would it be possible for you to release an -alpha or -rc version to NPM of 3.0.0?

Kind regards,
Tarjei

**Comment by brettz9** [comment] 2017-04-19 23:55
Thankfully as per https://github.com/axemclion/IndexedDBShim/issues/262#issuecomment-294339093 , we have just become ready for this now, but I need @axemclion to get the npm publishing part set in motion. I'm closing this issue as it is effectively a dupe of #262.

Btw, you may also be interested in tracking https://github.com/tmpvar/jsdom/issues/1748 to get jsdom support more readily integrated.

**Closed as completed by brettz9** 2017-04-19 23:55 UTC
