### ISSUE TITLE
shim indexeddb works on ios 8 but doesnt work on ios 9

### ISSUE THREAD

**Issue by Josephdias92** [indexeddbshim/IndexedDBShim#252] opened 2016-06-22 07:09 UTC
i installed shimindexed in my application to support home screen in ios. its working for home screen and safari but it doesnt work on chrome and other browser. 

on ios 8 everything works fine but in ios 9 chrome and other browser it doesn't work.

**Comment by brettz9** [comment] 2016-06-22 13:39
First of all, how did you install? Secondly, please provide a test case which shows which code is not working, or at least provide a console error message with a description of where the code fails. Did you call `shimIndexedDB.__useShim();`?

I also wonder whether this is a duplicate of #220, #245, or #227

**Comment by Josephdias92** [comment] 2016-06-23 04:31
@brettz9 hello im using dexie library so i included shim just before dexie library.
this is the console error which im getting
[Error] TypeError: Attempted to assign to readonly property.

if i use `shimIndexedDB.__useShim();` it will force my application to use webSQL even if indexeddb is present. i want to use webSQL only if indexeddb is not present on browser.

i guess its related to #167 

``` js
(function() {
    // This works on all browsers, and only uses IndexedDBShim as a final fallback 
    var indexedDB = window.indexedDB || 
                    window.mozIndexedDB ||
                    window.webkitIndexedDB || 
                    window.msIndexedDB || 
                    window.shimIndexedDB;

    // This code will use the native IndexedDB, if it exists, or the shim
    indexedDB.open("MyDatabase", 1);
})();
```

this is the solution i liked but im not sure how to make it work with dexie

**Comment by brettz9** [comment] 2016-06-23 07:22
What line number is the console error pointing to?  What is the version of IndexedDB you are using? Did you install via npm? You could also post the code where the console points you...

FYI, there is some code which automatically calls the shim under certain circumstances. The current code which does this (and which I don't think has changed much in substance, even if it looks different) is the following:

``` js
    // Workaround to prevent an error in Firefox
    if (!('indexedDB' in IDB)) {
        IDB.indexedDB = IDB.indexedDB || IDB.webkitIndexedDB || IDB.mozIndexedDB || IDB.oIndexedDB || IDB.msIndexedDB;
    }
    let poorIndexedDbSupport = false;
    if (typeof navigator !== 'undefined' && (
        navigator.userAgent.match(/Android 2/) || navigator.userAgent.match(/Android 3/) || navigator.userAgent.match(/Android 4\.[0-3]/))
    ) {
        /* Chrome is an exception. It supports IndexedDb */
        if (!navigator.userAgent.match(/Chrome/)) {
            poorIndexedDbSupport = true;
        }
    }

    if ((IDB.indexedDB === undefined || !IDB.indexedDB || poorIndexedDbSupport) && CFG.win.openDatabase !== undefined) {
        IDB.shimIndexedDB.__useShim();
    }
```

I guess we just need to add some browser detection for iOS 9 if we can't feature detect.

You said, "on ios 8 everything works fine but in ios 9 chrome and other browser it doesn't work". What other browsers did you try for iOS 9?

**Comment by Josephdias92** [comment] 2016-06-23 08:51
@brettz9 i used bower to install this package. it works on safari and homescreen but doesnt work on chrome and mozilla (IOS 9).

**Comment by brettz9** [comment] 2016-06-23 14:14
@Josephdias92 : Thanks--I also need the line number of the error from console...

**Comment by brettz9** [comment] 2016-06-23 16:11
First, @Josephdias92,  if you are using Bower, please make sure you have the latest version of IndexedDBShim from Bower available (currently 2.2.1).

Second, immediately before this line...

``` js
if ((IDB.indexedDB === undefined || !IDB.indexedDB || poorIndexedDbSupport) && CFG.win.openDatabase !== undefined) {
```

...try putting the following code and then, if you could, report back on whether the various browser environments work as intended...Although I could probably find a way to test it through Saucelabs/PhantomJS, I appreciate your testing this for me.

``` js
if (
    typeof navigator !== 'undefined' && // Ignore Node or other environments
    (navigator.userAgent.indexOf('Safari') === -1 || navigator.userAgent.indexOf('Chrome') > -1) && // Exclude genuine Safari: http://stackoverflow.com/a/7768006/271577
    // Detect iOS: http://stackoverflow.com/questions/9038625/detect-if-device-is-ios/9039885#9039885
    // and detect version 9: http://stackoverflow.com/a/26363560/271577
    (/iPad|iPhone|iPod.* os 9_/i).test(navigator.userAgent) &&
    !window.MSStream // But avoid IE11
) {
    poorIndexedDbSupport = true;
}
```

**Comment by brettz9** [comment] 2016-06-23 18:45
That code should ensure that the shim is called, and only called when in iOS 9 non-Safari...

**Comment by Josephdias92** [comment] 2016-06-24 05:43
@brettz9 i wont be able to give you the line of code whether the error is occurring because concatenating and minifying all my vendor files before testing on ipad. and yes im using 2.2.1 version of IndexedDBShim. is there any other way i can override this code without modifying IndexedDBShim.js file.

**Comment by Josephdias92** [comment] 2016-06-24 07:04
@brettz9 where*

**Comment by brettz9** [comment] 2016-06-26 21:57
Instead of manually changing code, @Josephdias92 , can you try changing your project's bower dependency line for "IndexedDBShim" to `https://github.com/axemclion/IndexedDBShim#ios9` and running `bower install` in your project directory and letting us know what happens?

I've added code which should work to auto-shim non-Safari iOS9. Please note that this is based on our code in `master` and could have other interaction issues, and , but as things are working fine in Chrome, I hope you can test against this latest version. The only breaking change likely for most people would be if you were using the `IDBTransaction` constants which have been removed from IndexedDB and thus now also from `IndexedDBShim`.

**Comment by Josephdias92** [comment] 2016-06-27 10:21
@brettz9 this ios9 branch works fine on my ipad now. 

this code forces the app to use websql even if indexedDb is support on the browser right ?

**Comment by brettz9** [comment] 2016-06-27 13:46
Thanks for the report!

And correct, the new code will force WebSQL for non-Safari iOS9 (and continue to force it for old non-Chrome Android, versions 2-4.3). Will close now but feel to comment further as necessary.

**Closed as completed by brettz9** 2016-06-27 13:46 UTC
Labels: Bug-environment support
