### ISSUE TITLE
multiEntry index query error

### ISSUE THREAD

**Issue by gombiuda** [indexeddbshim/IndexedDBShim#222] opened 2015-09-08 00:42 UTC
Happy to see multiEntry is supported in #16 
But I may come into a bug for an index query for multiEntry.

I can query for a document which the multiEntry column contains an exactly value, but I can't do this in indexedDBShim. 

Here is the error:

```
[Error] TypeError: undefined is not a function (evaluating 'me.__range.upper.indexOf(me.__range.lower)')
    error (indexeddbshim.js, line 2698)
    executeNextRequest (indexeddbshim.js, line 2717)
    executeRequests (indexeddbshim.js, line 2722)
```

**Comment by brettz9** [comment] 2016-10-18 19:21
Can you provide some code that produces the error?

Of course, we should not expose such an error, but it looks like you may be getting this by using a range which uses non-array keys despite the fact that you were on a multiEntry index. Although this is allowable, I mention it because you might not have intended it.

I have at least avoided the error for now in `master` by checking for an array in the code you cited (and ensured our many tests show no regressions), but I can't guarantee other issues won't occur. I will close this for now as the specific problem is fixed, though feel free to reopen or file a new issue (with a test case) if you are still seeing problems despite the fix.

**Closed as completed by brettz9** 2016-10-18 19:21 UTC
Labels: Bug
